.TH wavemonrc 5 "December 2010" Linux "User Manuals"
.SH NAME
$HOME/.wavemonrc \- wavemon configuration file
.SH DESCRIPTION
\fIwavemonrc\fR is the per-user configuration file for \fBwavemon\fR(1).
This page describes its individual configuration options.  Each corresponds
to a configuration item of the \fIPreferences\fR screen (F7 key), whose
on-screen name is shown in parentheses.
.P
.B interface = <ifname>
.RS
.RE
.R (Interface)
.RS
Selects the wireless interface to use.
.P
.RE
.B cisco_mac = (on|off)
.RS
.RE
.R (Cisco-style MAC addresses)
.RS
If enabled, display MAC addresses using lower-case hex digits separated by dots
rather than colons.
.P
.RE
.B stat_updates = <n>
.RS
.RE
.R (Statistics updates)
.RS
Time interval for polling new statistics. Range: 10..4000ms.
.P
.RE
.B lhist_slot_size = <n>
.RS
.RE
.R (Histogram update cycles)
.RS
Number of samples used per each histogram slot. For example, if the stat_updates
interval is 500ms and the histogram slot size is 4, the histogram is moved
one slot further every 2 seconds. Range: 1..64.
.P
.RE
.B meter_smoothness = <n>
.RS
.RE
.R (Level meter smoothness)
.RS
Determines the responsiveness of level meters, tracking the moving average
rather than following each new sample. The given value specifies the percentage
of the history (the 'inertia') of preceding samples. A value of 0 disables
this option. Range: 0..99%.
.P
.RE
.B info_updates = <n>
.RS
.RE
.R (Dynamic info updates)
.RS
Sets refresh rate for dynamic device parameters (e.g. bitrate) and the
refresh interval for the Scan window (F3). Range: 1..60s.
.P
.RE
.B override_auto_scale = (on|off)
.RS
.RE
.R (Override scale autodetect)
.RS
Override the auto-scaling of the bar graphs and histogram, allowing you to set your own scales.
.P
.RE
.B min_signal_level, max_signal_level = <n>
.RS
.RE
.R (Minimum signal level, Maximum signal level)
.RS
Set the left and right boundaries of the signal level scales. Ranges: -128..-60dBm (minimum) and -59..120dBm (maximum).
.P
.RE
.B min_noise_level, max_noise_level = <n>
.RS
.RE
.R (Minimum noise level, Maximum noise level)
.RS
These work similar to the signal boundary settings. Ranges: -128..-60dBm
(minimum) and -60..120dBm (maximum).
.P
.RE
.B random = (on|off)
.RS
.RE
.R (Random signals)
.RS
Switches on a fancy random generator for testing.
.P
.RE
.B lo_threshold_action = (disabled|beep|flash|beep+flash)
.RS
.RE
.R (Low threshold action)
.RS
Issue a warning  at a given threshold at the lower end of the signal
scale. It is meant for alarming you when a signal appears at the receiver.
.P
.RE
.B lo_threshold = <n>
.RS
.RE
.R (Low threshold)
.RS
Sets the threshold value for the 'Low threshold action'.
Range: -120..-60dBm.
.P
.RE
.B hi_threshold_action = (disabled|beep|flash|beep+flash)
.RS
.RE
.R (High threshold action)
.RS
Analogous to lo_threshold_action, only this time the threshold is at
the upper end of the scale and the action is performed when the signal level
drops below it. The acoustic signal is also different in order to be easily
distinguishable from the lower one. Correctly adjusted, this little fellow
will tell you when you should move closer to the base station.
.P
.RE
.B hi_threshold = <n>
.RS
.RE
.R (High threshold)
.RS
Sets the threshold for the 'High threshold action'. Range: -59..120dBm.
.P
.RE
.B startup_screen = (info|histogram|scan window)
.RS
.RE
.R (Startup screen)
.RS
Which of the screens appears at program startup.
.SH "AUTHOR"
Written by Jan Morgenstern <jan@jm-music.de>.
.SH "REPORTING BUGS"
Send bug reports and/or suggestions to Gerrit Renker <gerrit@erg.abdn.ac.uk>.
.SH "COPYRIGHT"
This is free software with ABSOLUTELY NO WARRANTY. See file COPYING for details.
